services:
  reflector:
    image: z1xs4xg62/reflector:latest-alpine
    ports:
      - 443:443
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./serverops/camo/templates:/app/serverops/camo/templates
