services:
  reflector:
    image: ghcr.io/cnc5/reflector:latest-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./serverops/camo/templates:/app/serverops/camo/templates
      - /etc/letsencrypt:/etc/letsencrypt
