name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout github repo
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev.requirements.txt
    - name: Lint
      run: |
        # flake8 does not understand module __init__ imports and flags them as F401
        flake8 serverops/ --count --ignore=F401 --show-source --statistics
        flake8 serverops/ --count --exit-zero --max-complexity=10 --statistics

        # Not conformant yet
        #mypy --strict serverops/
